---
allowBuilds:
  "@vscode/vsce-sign": true
  esbuild: true
  keytar: true
  tree-sitter-javascript: true
  tree-sitter-json: true
  tree-sitter-typescript: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.2.1
minimumReleaseAgeExclude:
  - '@sveltejs/kit@2.67.0'
  - cookie@0.7.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
